apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: microservice-backend
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: microservice-frontend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort